//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class ManipulationMsg : Message
    {
        public const string k_RosMessageName = "manipulation/Manipulation";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg endpose;
        public Geometry.PoseMsg startpose;
        public long id;
        public string object_name;

        public ManipulationMsg()
        {
            this.endpose = new Geometry.PoseMsg();
            this.startpose = new Geometry.PoseMsg();
            this.id = 0;
            this.object_name = "";
        }

        public ManipulationMsg(Geometry.PoseMsg endpose, Geometry.PoseMsg startpose, long id, string object_name)
        {
            this.endpose = endpose;
            this.startpose = startpose;
            this.id = id;
            this.object_name = object_name;
        }

        public static ManipulationMsg Deserialize(MessageDeserializer deserializer) => new ManipulationMsg(deserializer);

        private ManipulationMsg(MessageDeserializer deserializer)
        {
            this.endpose = Geometry.PoseMsg.Deserialize(deserializer);
            this.startpose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
            deserializer.Read(out this.object_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.endpose);
            serializer.Write(this.startpose);
            serializer.Write(this.id);
            serializer.Write(this.object_name);
        }

        public override string ToString()
        {
            return "ManipulationMsg: " +
            "\nendpose: " + endpose.ToString() +
            "\nstartpose: " + startpose.ToString() +
            "\nid: " + id.ToString() +
            "\nobject_name: " + object_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
