//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlaneDetection
{
    [Serializable]
    public class PlaneDetectionResponse : Message
    {
        public const string k_RosMessageName = "plane_detection/PlaneDetection";
        public override string RosMessageName => k_RosMessageName;

        public string results;
        public Geometry.Vector3Msg corner1;
        public Geometry.Vector3Msg corner2;
        public Geometry.Vector3Msg corner3;
        public Geometry.Vector3Msg corner4;

        public PlaneDetectionResponse()
        {
            this.results = "";
            this.corner1 = new Geometry.Vector3Msg();
            this.corner2 = new Geometry.Vector3Msg();
            this.corner3 = new Geometry.Vector3Msg();
            this.corner4 = new Geometry.Vector3Msg();
        }

        public PlaneDetectionResponse(string results, Geometry.Vector3Msg corner1, Geometry.Vector3Msg corner2, Geometry.Vector3Msg corner3, Geometry.Vector3Msg corner4)
        {
            this.results = results;
            this.corner1 = corner1;
            this.corner2 = corner2;
            this.corner3 = corner3;
            this.corner4 = corner4;
        }

        public static PlaneDetectionResponse Deserialize(MessageDeserializer deserializer) => new PlaneDetectionResponse(deserializer);

        private PlaneDetectionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.results);
            this.corner1 = Geometry.Vector3Msg.Deserialize(deserializer);
            this.corner2 = Geometry.Vector3Msg.Deserialize(deserializer);
            this.corner3 = Geometry.Vector3Msg.Deserialize(deserializer);
            this.corner4 = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.results);
            serializer.Write(this.corner1);
            serializer.Write(this.corner2);
            serializer.Write(this.corner3);
            serializer.Write(this.corner4);
        }

        public override string ToString()
        {
            return "PlaneDetectionResponse: " +
            "\nresults: " + results.ToString() +
            "\ncorner1: " + corner1.ToString() +
            "\ncorner2: " + corner2.ToString() +
            "\ncorner3: " + corner3.ToString() +
            "\ncorner4: " + corner4.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
