//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PlaneDetection
{
    [Serializable]
    public class PlaneDetectionRequest : Message
    {
        public const string k_RosMessageName = "plane_detection/PlaneDetection";
        public override string RosMessageName => k_RosMessageName;

        public bool start;

        public PlaneDetectionRequest()
        {
            this.start = false;
        }

        public PlaneDetectionRequest(bool start)
        {
            this.start = start;
        }

        public static PlaneDetectionRequest Deserialize(MessageDeserializer deserializer) => new PlaneDetectionRequest(deserializer);

        private PlaneDetectionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
        }

        public override string ToString()
        {
            return "PlaneDetectionRequest: " +
            "\nstart: " + start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
