//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class BoundingBox2DArrayMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/BoundingBox2DArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public BoundingBox2DMsg[] boxes;

        public BoundingBox2DArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.boxes = new BoundingBox2DMsg[0];
        }

        public BoundingBox2DArrayMsg(Std.HeaderMsg header, BoundingBox2DMsg[] boxes)
        {
            this.header = header;
            this.boxes = boxes;
        }

        public static BoundingBox2DArrayMsg Deserialize(MessageDeserializer deserializer) => new BoundingBox2DArrayMsg(deserializer);

        private BoundingBox2DArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.boxes, BoundingBox2DMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.boxes);
            serializer.Write(this.boxes);
        }

        public override string ToString()
        {
            return "BoundingBox2DArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nboxes: " + System.String.Join(", ", boxes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
