//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Classification3DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Classification3D";
        public override string RosMessageName => k_RosMessageName;

        //  Defines a 3D classification result.
        // 
        //  This result does not contain any position information. It is designed for
        //    classifiers, which simply provide probabilities given a source image.
        public HeaderMsg header;
        //  Class probabilities
        public ObjectHypothesisMsg[] results;
        //  The 3D data that generated these results (i.e. region proposal cropped out of
        //    the image). Not required for all detectors, so it may be empty.
        public Sensor.PointCloud2Msg source_cloud;

        public Classification3DMsg()
        {
            this.header = new HeaderMsg();
            this.results = new ObjectHypothesisMsg[0];
            this.source_cloud = new Sensor.PointCloud2Msg();
        }

        public Classification3DMsg(HeaderMsg header, ObjectHypothesisMsg[] results, Sensor.PointCloud2Msg source_cloud)
        {
            this.header = header;
            this.results = results;
            this.source_cloud = source_cloud;
        }

        public static Classification3DMsg Deserialize(MessageDeserializer deserializer) => new Classification3DMsg(deserializer);

        private Classification3DMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, ObjectHypothesisMsg.Deserialize, deserializer.ReadLength());
            this.source_cloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.Write(this.source_cloud);
        }

        public override string ToString()
        {
            return "Classification3DMsg: " +
            "\nheader: " + header.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nsource_cloud: " + source_cloud.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
