//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection2DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection2D";
        public override string RosMessageName => k_RosMessageName;

        //  Defines a 2D detection result.
        // 
        //  This is similar to a 2D classification, but includes position information,
        //    allowing a classification result for a specific crop or image point to
        //    to be located in the larger image.
        public HeaderMsg header;
        //  Class probabilities
        public ObjectHypothesisWithPoseMsg[] results;
        //  2D bounding box surrounding the object.
        public BoundingBox2DMsg bbox;
        //  The 2D data that generated these results (i.e. region proposal cropped out of
        //    the image). Not required for all use cases, so it may be empty.
        public Sensor.ImageMsg source_img;

        public Detection2DMsg()
        {
            this.header = new HeaderMsg();
            this.results = new ObjectHypothesisWithPoseMsg[0];
            this.bbox = new BoundingBox2DMsg();
            this.source_img = new Sensor.ImageMsg();
        }

        public Detection2DMsg(HeaderMsg header, ObjectHypothesisWithPoseMsg[] results, BoundingBox2DMsg bbox, Sensor.ImageMsg source_img)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.source_img = source_img;
        }

        public static Detection2DMsg Deserialize(MessageDeserializer deserializer) => new Detection2DMsg(deserializer);

        private Detection2DMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, ObjectHypothesisWithPoseMsg.Deserialize, deserializer.ReadLength());
            this.bbox = BoundingBox2DMsg.Deserialize(deserializer);
            this.source_img = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.Write(this.bbox);
            serializer.Write(this.source_img);
        }

        public override string ToString()
        {
            return "Detection2DMsg: " +
            "\nheader: " + header.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nbbox: " + bbox.ToString() +
            "\nsource_img: " + source_img.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
