//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection2DArrayMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection2DArray";
        public override string RosMessageName => k_RosMessageName;

        //  A list of 2D detections, for a multi-object 2D detector.
        public HeaderMsg header;
        //  A list of the detected proposals. A multi-proposal detector might generate
        //    this list with many candidate detections generated from a single input.
        public Detection2DMsg[] detections;

        public Detection2DArrayMsg()
        {
            this.header = new HeaderMsg();
            this.detections = new Detection2DMsg[0];
        }

        public Detection2DArrayMsg(HeaderMsg header, Detection2DMsg[] detections)
        {
            this.header = header;
            this.detections = detections;
        }

        public static Detection2DArrayMsg Deserialize(MessageDeserializer deserializer) => new Detection2DArrayMsg(deserializer);

        private Detection2DArrayMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.detections, Detection2DMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.detections);
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "Detection2DArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ndetections: " + System.String.Join(", ", detections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
