//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class ObjectHypothesisMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/ObjectHypothesis";
        public override string RosMessageName => k_RosMessageName;

        //  An object hypothesis that contains no position information.
        //  The unique numeric ID of object detected. To get additional information about
        //    this ID, such as its human-readable name, listeners should perform a lookup
        //    in a metadata database. See vision_msgs/VisionInfo.msg for more detail.
        public long id;
        //  The probability or confidence value of the detected object. By convention,
        //    this value should lie in the range [0-1].
        public double score;

        public ObjectHypothesisMsg()
        {
            this.id = 0;
            this.score = 0.0;
        }

        public ObjectHypothesisMsg(long id, double score)
        {
            this.id = id;
            this.score = score;
        }

        public static ObjectHypothesisMsg Deserialize(MessageDeserializer deserializer) => new ObjectHypothesisMsg(deserializer);

        private ObjectHypothesisMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.score);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.score);
        }

        public override string ToString()
        {
            return "ObjectHypothesisMsg: " +
            "\nid: " + id.ToString() +
            "\nscore: " + score.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
