//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class ManipulationSequenceResponse : Message
    {
        public const string k_RosMessageName = "manipulation/ManipulationSequence";
        public override string RosMessageName => k_RosMessageName;

        public string result;

        public ManipulationSequenceResponse()
        {
            this.result = "";
        }

        public ManipulationSequenceResponse(string result)
        {
            this.result = result;
        }

        public static ManipulationSequenceResponse Deserialize(MessageDeserializer deserializer) => new ManipulationSequenceResponse(deserializer);

        private ManipulationSequenceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "ManipulationSequenceResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
