//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class ManipulationSequenceRequest : Message
    {
        public const string k_RosMessageName = "manipulation/ManipulationSequence";
        public override string RosMessageName => k_RosMessageName;

        public ManipulationMsg[] manipulation_sequence;
        public string message;

        public ManipulationSequenceRequest()
        {
            this.manipulation_sequence = new ManipulationMsg[0];
            this.message = "";
        }

        public ManipulationSequenceRequest(ManipulationMsg[] manipulation_sequence, string message)
        {
            this.manipulation_sequence = manipulation_sequence;
            this.message = message;
        }

        public static ManipulationSequenceRequest Deserialize(MessageDeserializer deserializer) => new ManipulationSequenceRequest(deserializer);

        private ManipulationSequenceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.manipulation_sequence, ManipulationMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.manipulation_sequence);
            serializer.Write(this.manipulation_sequence);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ManipulationSequenceRequest: " +
            "\nmanipulation_sequence: " + System.String.Join(", ", manipulation_sequence.ToList()) +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
