//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class ManipulationSequenceResponse : Message
    {
        public const string k_RosMessageName = "manipulation/ManipulationSequence";
        public override string RosMessageName => k_RosMessageName;

        public string result;
        public sbyte status;

        public ManipulationSequenceResponse()
        {
            this.result = "";
            this.status = 0;
        }

        public ManipulationSequenceResponse(string result, sbyte status)
        {
            this.result = result;
            this.status = status;
        }

        public static ManipulationSequenceResponse Deserialize(MessageDeserializer deserializer) => new ManipulationSequenceResponse(deserializer);

        private ManipulationSequenceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "ManipulationSequenceResponse: " +
            "\nresult: " + result.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
