//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Manipulation
{
    [Serializable]
    public class TFtransformResponse : Message
    {
        public const string k_RosMessageName = "manipulation/TFtransform";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TransformMsg transform;
        public Tf2.TF2ErrorMsg error;
        public string source_frame;
        public string target_frame;

        public TFtransformResponse()
        {
            this.transform = new Geometry.TransformMsg();
            this.error = new Tf2.TF2ErrorMsg();
            this.source_frame = "";
            this.target_frame = "";
        }

        public TFtransformResponse(Geometry.TransformMsg transform, Tf2.TF2ErrorMsg error, string source_frame, string target_frame)
        {
            this.transform = transform;
            this.error = error;
            this.source_frame = source_frame;
            this.target_frame = target_frame;
        }

        public static TFtransformResponse Deserialize(MessageDeserializer deserializer) => new TFtransformResponse(deserializer);

        private TFtransformResponse(MessageDeserializer deserializer)
        {
            this.transform = Geometry.TransformMsg.Deserialize(deserializer);
            this.error = Tf2.TF2ErrorMsg.Deserialize(deserializer);
            deserializer.Read(out this.source_frame);
            deserializer.Read(out this.target_frame);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transform);
            serializer.Write(this.error);
            serializer.Write(this.source_frame);
            serializer.Write(this.target_frame);
        }

        public override string ToString()
        {
            return "TFtransformResponse: " +
            "\ntransform: " + transform.ToString() +
            "\nerror: " + error.ToString() +
            "\nsource_frame: " + source_frame.ToString() +
            "\ntarget_frame: " + target_frame.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
